In [2]:
import numpy as np

In [3]:
# numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
# 只能存相同类型的元素,为了能够随机访问
a = np.array((0,1,2,3),dtype=np.float64)
b = np.array([[0,1,2,3],[4,5,6,7]])
print("a=\n",a)
print("b=\n",b)

a=
 [0. 1. 2. 3.]
b=
 [[0 1 2 3]
 [4 5 6 7]]


In [14]:
a = np.array((0,1,2,3,4),dtype=np.float64)
b = np.array([[0,1,2,3],[4,5,6,7]],dtype=np.float64)
print("a.shape:",a.shape,"b.shape:",b.shape)
print("a.type:",type(a),"b.type:",type(b))
print("a.dtype:",a.dtype,"b.dtype:",b.dtype)
print(b.strides)

a.shape: (5,) b.shape: (2, 4)
a.type: <class 'numpy.ndarray'> b.type: <class 'numpy.ndarray'>
a.dtype: float64 b.dtype: float64
(32, 8)


In [18]:
b = np.array([[0,1,2,3],[4,5,6,7]])
a = b.reshape((4,2))# a,b在内存中共享一块内存
print(a)
print(b)
b[1][2] = 9999
c = a.astype(np.float64)# a,b在内存中独立
a[3][1] = 1888
print(a)
print(b)
print(c)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[   0    1]
 [   2    3]
 [   4    5]
 [9999 1888]]
[[   0    1    2    3]
 [   4    5 9999 1888]]
[[0.000e+00 1.000e+00]
 [2.000e+00 3.000e+00]
 [4.000e+00 5.000e+00]
 [9.999e+03 7.000e+00]]


In [31]:
import sys
b = np.array([[0,1,2,3],[4,5,6,7]],dtype=np.int16) #换成不同类型
a = b.reshape((4,-1))# a,b在内存中共享一块内存
print(a)
print(b)
print(a.strides) # 步幅
print(b.strides)
print(a.itemsize)
print(b.itemsize)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]
(4, 2)
(8, 2)
2
2


In [33]:
#快速生成等差数列
print("np.arange(0,1,0.1):\n",np.arange(0,1,0.1))

np.arange(0,1,0.1):
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [3]:
import numpy as np
print("np.linspace(0,1,10)\n",np.linspace(0,1,10))
print("np.linspace(0,1,10,endpoint=False)\n",np.linspace(0,1,10,endpoint=False))


np.linspace(0,1,10)
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
np.linspace(0,1,10,endpoint=False)
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [8]:
#等比数列
import numpy as np
print(np.logspace(0,2,5,endpoint=False)) # 10^0   ~    10^2    contain no 10^2
print(np.logspace(0,2,5))
print(np.logspace(0,4,5,base=2))
print(np.logspace(0,4,5,base=2,endpoint=False))

[ 1.          2.51188643  6.30957344 15.84893192 39.81071706]
[  1.           3.16227766  10.          31.6227766  100.        ]
[ 1.  2.  4.  8. 16.]
[1.         1.74110113 3.03143313 5.27803164 9.18958684]


In [16]:
#zeros
print(np.zeros((2,3),np.int32))
print(np.empty(4,np.float64)) # 不对数组进行初始化
print(np.ones((2,2),np.int32))
print(np.full(3,np.pi))
print(np.full((10,10),0))


[[0 0 0]
 [0 0 0]]
[2.12199579e-314 1.08646184e-311 8.81413112e-321 1.11362340e-308]
[[1 1]
 [1 1]]
[3.14159265 3.14159265 3.14159265]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [18]:
# function init

def weekday(i):
    return (i+6) % 7

print(np.fromfunction(weekday,(31,)).astype(np.int32))

[6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1]


In [21]:
def multy(i,j):
    return (i+1)*(j+1)

print(np.fromfunction(multy,(9,9)).astype(np.int32))

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [28]:
#一维元素的存取

import numpy as np

a = np.arange(10)
print(a)
print(a[1:3])
print(a[2])
print(a[:])
print(a[-5])
print(a[:-5])
a[:3] = 77,88,99
print(a)
#numpy数组使用切片，所得新数组与原数组共享内存，是原数组的视图
#list数组使用切片，所得的新数组是原数组的复制


[0 1 2 3 4 5 6 7 8 9]
[1 2]
2
[0 1 2 3 4 5 6 7 8 9]
5
[0 1 2 3 4]
[77 88 99  3  4  5  6  7  8  9]


In [33]:
import numpy as np
na = np.arange(10)
nb = na[1:3]
a = list(range(10))
b = a[1:3]
print("na:\n",na)
print("nb:\n",nb)
print("a:\n",a)
print("b:\n",b)
na[2] = 100
a[2] = 100
print("*************")
print("na:\n",na)
print("nb:\n",nb)
print("a:\n",a)
print("b:\n",b)

na:
 [0 1 2 3 4 5 6 7 8 9]
nb:
 [1 2]
a:
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b:
 [1, 2]
*************
na:
 [  0   1 100   3   4   5   6   7   8   9]
nb:
 [  1 100]
a:
 [0, 1, 100, 3, 4, 5, 6, 7, 8, 9]
b:
 [1, 2]


In [35]:
#使用整数列表获取数组
na = np.arange(10)
nb = na[[1,3,5,7]]
nb[1] = 99
nb[[2,3]] = 4396,7777
print(na)
print(nb)

[0 1 2 3 4 5 6 7 8 9]
[   1   99 4396 7777]


In [38]:
#使用整数数组作为下标
na = np.arange(10)
idx = np.array([[2,4,-6,5],[7,7,3,9]])
nb = na[idx] #一种新的获得数组的方法
print(na)
print(nb)

[0 1 2 3 4 5 6 7 8 9]
[[2 4 4 5]
 [7 7 3 9]]


In [43]:
#使用布尔列表作为下标
na = np.arange(10)
idx1 = [True,False,True,False,True,False,True,False,True,False]
print("na[idx1]:\n",na[idx1])
idx2 = (na%2==0)
print(type(idx2))
print(idx2)
print(na[idx2])

na[idx1]:
 [0 2 4 6 8]
<class 'numpy.ndarray'>
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
